# Generated by Django 5.2 on 2026-01-26 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='video')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2026, 1, 26, 10, 5, 31, 425794, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
