# Generated by Django 5.2 on 2026-01-26 10:58

import cloudinary_storage.storage
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 10, 58, 0, 454963, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='video'),
        ),
    ]
