# Generated by Django 5.2 on 2026-01-27 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamer', '0002_alter_video_uploaded_at_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 5, 41, 43, 248516, tzinfo=datetime.timezone.utc)),
        ),
    ]
